### ISSUE TITLE
Unable to Launch Caprine on Windows 10

### ISSUE THREAD

**Issue by wulfalpha** [sindresorhus/caprine#1031]
After installing the latest version of Caprine on windows 10 Enterprise Caprine will not start. (No window appears, nothing on the taskbar and nothing in the system tray) but when I look in the task manager it shows to caprine tasks not doing anything. of windows is 18362. No errors that I can see

**Comment by wulfalpha** [comment]
Logfile in appdata roaming says [2019-08-08 17:41:17.733] [info] Checking for update
[2019-08-08 17:41:20.610] [info] Update for version 2.35.0 is not available (latest version: 2.35.0, downgrade is disallowed). a bunch of times

**Comment by terrymunro** [comment]
This problem also occurring in Ubuntu 19.04.

**Comment by TomFaulkner** [comment]
Pop 19.04, an Ubuntu derivative.

```
~/snap/ A JavaScript error occurred in the main process
Uncaught Exception:
Error: EPERM: operation not permitted, chown '/home/tom/snap/caprine/26/.config/Caprine/config.json.1461117785'
    at Object.chownSync (fs.js:1104:3)
    at Function.writeFileSync [as sync] (/snap/caprine/26/resources/app.asar/node_modules/conf/node_modules/write-file-atomic/index.js:196:27)
    at ElectronStore.set store [as store] (/snap/caprine/26/resources/app.asar/node_modules/conf/index.js:277:19)
    at ElectronStore.set (/snap/caprine/26/resources/app.asar/node_modules/conf/index.js:152:14)
    at updateVibrancySetting (/snap/caprine/26/resources/app.asar/dist-js/config.js:149:15)
    at migrate (/snap/caprine/26/resources/app.asar/dist-js/config.js:159:5)
    at Object.<anonymous> (/snap/caprine/26/resources/app.asar/dist-js/config.js:162:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
/usr/share/libdrm/amdgpu.ids: No such file or directory
```

**Comment by KTsarlz** [comment]
Only white screen for me on Windows 10 and on the latest release

**Comment by wulfalpha** [comment]
For people using snap on linux: try this command and see if it lets Caprine run on your system.
sudo snap revert caprine
It worked on my solus but as windows and mac don't use mac I haven't found anything that works yet

**Comment by xavierbriole** [comment]
I have the same bug on macOS

**Comment by TomFaulkner** [comment]
Unfortunately before looking for issues I did some troubleshooting, including uninstalling, so I have no versions to revert too.

**Comment by Chnossos** [comment]
Clean install on a Windows 10 Family Edition 1903 (18362.267). Nothing comes up and the console says:
```
 22:06:29.653 > Checking for update
(node:4284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (C:\Users\Pierre\AppData\Local\Programs\caprine\resources\app.asar\dist-js\index.js:190:28)
    at C:\Users\Pierre\AppData\Local\Programs\caprine\resources\app.asar\dist-js\index.js:240:18
(node:4284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (C:\Users\Pierre\AppData\Local\Programs\caprine\resources\app.asar\dist-js\index.js:190:28)
    at C:\Users\Pierre\AppData\Local\Programs\caprine\resources\app.asar\dist-js\index.js:240:18
(node:4284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
22:06:32.499 > Update for version 2.35.0 is not available (latest version: 2.35.0, downgrade is disallowed).
```

**Comment by CyberDuck79** [comment]
Same problem on macOS Mojave : 
`21:17:59.208 › Checking for update
(node:7406) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/Applications/Caprine.app/Contents/Resources/app.asar/dist-js/index.js:190:28)
    at /Applications/Caprine.app/Contents/Resources/app.asar/dist-js/index.js:240:18
(node:7406) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/Applications/Caprine.app/Contents/Resources/app.asar/dist-js/index.js:190:28)
    at /Applications/Caprine.app/Contents/Resources/app.asar/dist-js/index.js:240:18
(node:7406) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7406) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7406) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7406) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
21:18:01.324 › Update for version 2.35.0 is not available (latest version: 2.35.0, downgrade is disallowed).
`

**Comment by prediscover** [comment]
on a clean install on MacOS Mojave, caprine is running according to activity monitor but no window comes up. Temporarily reverting to 2.34

**Comment by sindresorhus** [comment]
> (node:7406) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined

@whitecrownclown Looks related to your electron-store PR.

**Comment by whitecrownclown** [comment]
I'll have a look asap.

**Comment by gaui** [comment]
@whitecrownclown This is not solved.

Installed as Snap. Tried reinstalling without success.
https://askubuntu.com/q/1167647/319899

Error:

```
gaui@gauiPC:/$ snap run caprine
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EPERM: operation not permitted, chown '/home/gaui/snap/caprine/28/.config/Caprine/config.json.368971289'
    at Object.chownSync (fs.js:1104:3)
    at Function.writeFileSync [as sync] (/snap/caprine/28/resources/app.asar/node_modules/conf/node_modules/write-file-atomic/index.js:196:27)
    at ElectronStore.set store [as store] (/snap/caprine/28/resources/app.asar/node_modules/conf/index.js:277:19)
    at ElectronStore.set (/snap/caprine/28/resources/app.asar/node_modules/conf/index.js:152:14)
    at updateVibrancySetting (/snap/caprine/28/resources/app.asar/dist-js/config.js:155:15)
    at migrate (/snap/caprine/28/resources/app.asar/dist-js/config.js:165:5)
    at Object.<anonymous> (/snap/caprine/28/resources/app.asar/dist-js/config.js:168:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
```

lsb_release:

```
Distributor ID:	LinuxMint
Description:	Linux Mint 19.2 Tina
Release:	19.2
Codename:	tina
```

```
gaui@gauiPC:/$ snap info caprine --verbose
name:      caprine
summary:   Caprine
publisher: Sindre Sorhus (sindresorhus)
license:   unset
description: |
  Caprine is an unofficial and privacy-focused Facebook Messenger app with many useful features.
commands:
  - caprine
notes:               
  private:           false
  confinement:       strict
  devmode:           false
  jailmode:          false
  trymode:           false
  enabled:           true
  broken:            false
  ignore-validation: false
base:         core18
snap-id:      UluDLd64Rry6IYTesGapYwu8sfuZmwbu
tracking:     stable
refresh-date: today at 21:21 GMT
channels:
  stable:    2.37.0 2019-08-21 (28) 54MB -
  candidate: ↑                           
  beta:      ↑                           
  edge:      ↑                           
installed:   2.37.0            (28) 54MB -
```
