### ISSUE TITLE
"Error: EPERM: operation not permitted, chown" with Caprine 2.35.0 from Snap on Ubuntu

### ISSUE THREAD

**Issue by tkedwards** [sindresorhus/caprine#1032]
Hi,

With the latest version of the Snap 2.35.0 2019-08-08 (26) Caprine crashes on startup and cannot be run:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EPERM: operation not permitted, chown '/home/tim/snap/caprine/26/.config/Caprine/config.json.1795270895'
    at Object.chownSync (fs.js:1104:3)
    at Function.writeFileSync [as sync] (/snap/caprine/26/resources/app.asar/node_modules/conf/node_modules/write-file-atomic/index.js:196:27)
    at ElectronStore.set store [as store] (/snap/caprine/26/resources/app.asar/node_modules/conf/index.js:277:19)
    at ElectronStore.set (/snap/caprine/26/resources/app.asar/node_modules/conf/index.js:152:14)
    at updateVibrancySetting (/snap/caprine/26/resources/app.asar/dist-js/config.js:149:15)
    at migrate (/snap/caprine/26/resources/app.asar/dist-js/config.js:159:5)
    at Object.<anonymous> (/snap/caprine/26/resources/app.asar/dist-js/config.js:162:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)

```

I ran 'snap revert caprine' and with Caprine 2.34.0 (25) the issue does not happen

Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Comment by sebous** [comment]
I have the same error on Fedora 30 kernel 5.2.6

**Comment by prashun-chitkr** [comment]
having same issue Ubuntu 18.04 kernel 5.0

**Comment by lyubolp** [comment]
I have the same issue - Kubuntu 19.04, kernel 5.0

**Comment by PrzemyslawPradela** [comment]
The same on Xubuntu 18.04, kernel 5.0

**Comment by sebous** [comment]
version 2.36 fixed the problem for me, great work!

**Comment by whitecrownclown** [comment]
@sindresorhus 
I think the issue might be [here](https://github.com/npm/write-file-atomic/issues/50) since [conf](https://github.com/sindresorhus/conf) uses [write-file-atomic](https://github.com/npm/write-file-atomic) under the hood.

**Comment by tkedwards** [comment]
Yep 2.36.0 works for me too, thanks!

**Comment by jstevans** [comment]
@tkedwards @sindresorhus I'm seeing this in 2.37.0, even after removing and reinstalling the snap :cry:

**Comment by tkedwards** [comment]
Same, I've opened https://github.com/sindresorhus/caprine/issues/1062

**Comment by Remyks** [comment]
You could try 
`rm ~/.config/Caprine/config.json`
OR
`chgrp $USER ~/.config/Caprine/config.json`

It worked for me after the update

**Comment by tkedwards** [comment]
Doesn't work for me:

```
$ LANG=en_us ls -l ~/.config/Caprine/config.json
ls: cannot access '/home/tim/.config/Caprine/config.json': No such file or directory
```

```
$ caprine
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EPERM: operation not permitted, chown '/home/tim/snap/caprine/28/.config/Caprine/config.json.1321259779'
    at Object.chownSync (fs.js:1104:3)
    at Function.writeFileSync [as sync] (/snap/caprine/28/resources/app.asar/node_modules/conf/node_modules/write-file-atomic/index.js:196:27)
    at ElectronStore.set store [as store] (/snap/caprine/28/resources/app.asar/node_modules/conf/index.js:277:19)
    at ElectronStore.set (/snap/caprine/28/resources/app.asar/node_modules/conf/index.js:152:14)
    at updateVibrancySetting (/snap/caprine/28/resources/app.asar/dist-js/config.js:155:15)
    at migrate (/snap/caprine/28/resources/app.asar/dist-js/config.js:165:5)
    at Object.<anonymous> (/snap/caprine/28/resources/app.asar/dist-js/config.js:168:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
```

```
$ ls -l /home/tim/snap/caprine/28/.config/Caprine/config.json
-rw-rw---- 1 tim tim 837 Aug 29 00:48 /home/tim/snap/caprine/28/.config/Caprine/config.j
```

Have I missed something?

**Comment by Remyks** [comment]
ahem I didn't installed caprine on ubuntu with snap .. I installed it on arch
In the issue you've opened people said me that the problem come from snap .. (even in I had exactly word for word the same error ... weird)

And I don't have ubuntu, So I can't test ...
Oh .. I've just seen, try to do `sudo chmod a+r /home/tim/snap/caprine/28/.config/Caprine/config.json`
