### ISSUE TITLE
Failed to launch on Ubuntu new install

### ISSUE THREAD

**Issue by Rookie001MC** [sindresorhus/caprine#1034]
I reinstalled Caprine from the Ubuntu Store and when I launched it, I got an error:
```
 A JavaScript error occurred in the main process
Uncaught Exception:
Error: Config schema violation: `emojiStyle` should be equal to one of the allowed values
    at ElectronStore._validate (/opt/Caprine/resources/app.asar/node_modules/conf/index.js:111:10)
    at ElectronStore.get store [as store] (/opt/Caprine/resources/app.asar/node_modules/conf/index.js:246:9)
    at new Conf (/opt/Caprine/resources/app.asar/node_modules/conf/index.js:92:26)
    at new ElectronStore (/opt/Caprine/resources/app.asar/node_modules/electron-store/index.js:23:3)
    at Object.<anonymous> (/opt/Caprine/resources/app.asar/dist-js/config.js:161:15)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
```

I removed the snap version and installed the .deb version and it got the same error.

**Comment by sindresorhus** [comment]
// @whitecrownclown
