### ISSUE TITLE
Caprine hangs on startup

### ISSUE THREAD

**Issue by QkiZMR** [sindresorhus/caprine#1043]
... with error:
```
(node:10444) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/opt/Caprine/resources/app.asar/dist-js/index.js:190:28)
    at /opt/Caprine/resources/app.asar/dist-js/index.js:240:18
(node:10444) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/opt/Caprine/resources/app.asar/dist-js/index.js:190:28)
    at /opt/Caprine/resources/app.asar/dist-js/index.js:240:18
(node:10444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:10444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
after running from command line. No prompt returned, no window, nothing.

**Comment by whitecrownclown** [comment]
@QkiZMR Related to this [issue](https://github.com/sindresorhus/caprine/issues/1031).
You can download `v2.36.0` which should work just fine.

**Comment by QkiZMR** [comment]
Thanks for quick response. 2.36 works fine.
