### ISSUE TITLE
UnhandledPromiseRejecationWarning when trying to start caprine

### ISSUE THREAD

**Issue by kharann** [sindresorhus/caprine#1069]
This is the error i got. Dont really know why since this should be the newest version. Arch xfce4

```
(node:7047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/usr/lib/caprine/dist-js/index.js:190:28)
    at /usr/lib/caprine/dist-js/index.js:240:18
(node:7047) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'x' of undefined
    at createMainWindow (/usr/lib/caprine/dist-js/index.js:190:28)
    at /usr/lib/caprine/dist-js/index.js:240:18
(node:7047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Comment by CvX** [comment]
Please update Caprine to the latest version.
