### ISSUE TITLE
java script error

### ISSUE THREAD

**Issue by rymar1** [sindresorhus/caprine#1184]
Can't even install 2.41.1 on linux mine 19.1

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Config schema violation: `vibrancy` should be string; `vibrancy` should be equal to one of the allowed values
    at ElectronStore._validate (/opt/Caprine/resources/app.asar/node_modules/conf/index.js:154:10)
    at ElectronStore.get store [as store] (/opt/Caprine/resources/app.asar/node_modules/conf/index.js:429:9)
    at new Conf (/opt/Caprine/resources/app.asar/node_modules/conf/index.js:119:26)
    at new ElectronStore (/opt/Caprine/resources/app.asar/node_modules/electron-store/index.js:23:3)
    at Object.<anonymous> (/opt/Caprine/resources/app.asar/dist-js/config.js:163:15)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26

Currently unable to use

**Comment by bichou** [comment]
windows 7 x64, caprine version 2.39.0 
image https://ibb.co/f4bdDnP
after 2 min from open menu i get this error

**Comment by rymar1** [comment]
So it turns out this was caused by a new version install. I downloaded the latest .deb file. What I should've done before installing the new version was go to **.config** folder in **Home** and deleted the **Caprine** folder in it. Once I did do this all was fine.

**Comment by linoskoczek** [comment]
I confirm that removal of **.config/Caprine** solves the issue:

```
rm -rf ~/.config/Caprine
```

**Comment by myshon** [comment]
I just removed C:/Users/myname/AppData/Caprine and then it started working. Thanks!

**Comment by dusansimic** [comment]
AFAIK, this issue was due to Caprine config and is fixed in an older update and seems like removing old config fixes it. I will close this now.
