### ISSUE TITLE
Crash at startup (uncaught exception)

### ISSUE THREAD

**Issue by thegeek1977** [sindresorhus/caprine#1393]
Hi.

In the newest Linux Mint, Caprine crashes whenever I try to run it.

Tried to run it from a terminal and got this errors:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Config schema violation: `vibrancy` should be string; `vibrancy` should be equal to one of the allowed values
    at ElectronStore._validate (/opt/Caprine/resources/app.asar/node_modules/conf/index.js:154:10)
    at ElectronStore.get store [as store] (/opt/Caprine/resources/app.asar/node_modules/conf/index.js:441:9)
    at new Conf (/opt/Caprine/resources/app.asar/node_modules/conf/index.js:119:26)
    at new ElectronStore (/opt/Caprine/resources/app.asar/node_modules/electron-store/index.js:23:3)
    at Object.<anonymous> (/opt/Caprine/resources/app.asar/dist-js/config.js:197:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)

This is with the newest version of Caprine. Also there is no icon in the start menu. I am on the latest Linux Mint with Cinnamon.
How Come, and how can this eventually be solved?

**Comment by thegeek1977** [comment]
Also I forgot to mention that this is installed via the .deb file since I really don't like snap og AppImage. I'd rather run programs more natively as possible

**Comment by whitecrownclown** [comment]
@thegeek1977 This is an issue with older configuration files & `vibrancy` changes. Could you remove your `~/.config/Caprine` config file? I'm not sure of the exact path of the file.

**Comment by thegeek1977** [comment]
That solved it for me. Thank you very much.
