### ISSUE TITLE
Could not start after latest update 2.55.7 2022

### ISSUE THREAD

**Issue by manhnt9** [sindresorhus/caprine#1876]
![image](https://user-images.githubusercontent.com/11463928/183298492-280eea6b-35e1-4096-8d1d-544b19913b73.png)

OS: Ubuntu 20.04.4 LTS (snap version)

**Comment by tomaszduda23** [comment]
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-util/main'
Require stack:
- /snap/caprine/49/resources/app.asar/dist-js/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:779:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/snap/caprine/49/resources/app.asar/dist-js/index.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
```

**Comment by lefterisgar** [comment]
Temporarily, download [this release](https://github.com/lefterisgar/caprine/releases/tag/v2.55.7-2) until issues are resolved.

**Comment by manhnt9** [comment]
Thanks @lefterisgar, it works !
