### ISSUE TITLE
carpine locks on all new messages

### ISSUE THREAD

**Issue by cobra3282000** [sindresorhus/caprine#2033]
---

Caprine 2.57.4
Electron 24.1.3
linux 6.4.3-060403-generic
Locale: en-US

every time i get a message on caprine it freezes and locks.   every time.   cant do anything really except restart it.  not sure what is going on.   i started carpine terminal to see error messages, this is what i get.   dmeg shows no errors.  

checkForUpdatesAndNotify called, downloadPromise is null
(node:6684) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'checked')
    at /opt/Caprine/resources/app.asar/dist-js/browser.js:208:34
    at async EventEmitter.listener (/opt/Caprine/resources/app.asar/node_modules/electron-better-ipc/source/renderer.js:46:34)
(Use `caprine --trace-warnings ...` to show where the warning was created)
(node:6684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by JoelFeiner-viimed** [comment]
I'm getting this same error now on startup. Caprine no longer loads anything and freezes immediately. I cannot use it.

**Comment by JoelFeiner** [comment]
I'm getting this same issue. It happens on startup and it will not load new messages since Friday. It also freezes and never recovers. I can't use Caprine at all.

Also Caprine 2.57.4 via Snap on Ubuntu 23.04 (6.2.0-25-generic).

**Comment by cobra3282000** [comment]
mine does that on startup too, and some times it reloads and works, 99 percent of the time though i get a message and boom its locked.    but the menu bar still works, but settings wont open either.   i have tried on a few distro's, and same problem.  go figure, i also use linux mint 21.2 xfce and mate.

**Comment by gnar03** [comment]
Same issue here as of July 26. It worked fine before, now can't get it to work anymore at all.

**Comment by shauneccles** [comment]
Same issue on Win64 with 2.58.0

**Comment by cobra3282000** [comment]
my issues have changed now, now dark mode is not working, but the messenger part is working again, and cant make any changes to settings.    under linux, does any know where the settings are stored at ?   what directory ?   maybe manually edit the settings file ?

**Comment by cobra3282000** [comment]
I wanted to say thank you for fixing this problem.

**Comment by cobra3282000** [comment]
well it returned crashing on getting messages :(  i think facebook made changes again to there chat client.

**Comment by dusansimic** [comment]
I can't reproduce the issue at the moment so I can't really help much. PRs are welcome.

**Comment by ezvr** [comment]
I have the same issue.
version 2.58.

full lock-up and freeze on new incoming message.

**Comment by cobra3282000** [comment]
> I can't reproduce the issue at the moment so I can't really help much. PRs are welcome.

i udnerstand.   i think its something facebook is doing to there stuff, its a very strange issue.   i have noticed when it locks up it when i get a new message from someone.   there are no dmesg logs of errors either.   does caprine use your current broswer stuff ?  like to draw out the window that holds your messages and stuff ?  if so i wonder if its a chrome problem then ?

**Comment by dusansimic** [comment]
>  does caprine use your current broswer stuff ? like to draw out the window that holds your messages and stuff ? if so i wonder if its a chrome problem then ?

Caprine uses [Electron](https://electronjs.org) to essentially render the [Messenger website](https://messenger.com). Electron is based on the Chromium browser so it might be something related to it but that would mean it should also occur on the website when you use it through the regular browser, like Chromium.

**Comment by cobra3282000** [comment]
yeah if you open chrome it works greawt go figure.   i am not sure, who knows at this point, i really like the messenger caprine alot.   maybe it will works its self out, maybe its a linux thing though ?    i am using linux mint 21.2 mate i am not sure.   jsut its strange.   i dont get it.   hope fully it does works its self out though.

**Comment by mirenradia** [comment]
I just started getting this problem after updating to Caprine 2.58.1 from the Fedora COPR.

**Comment by haifisch88** [comment]
I also have this problem on Ubuntu 22.04 along with others such as messenger preferences unable to open. Are there any workarounds?
