### ISSUE TITLE
/usr/share/libdrm/amdgpu.ids: No such file or directory*

### ISSUE THREAD

**Issue by joinfok** [sindresorhus/caprine#2132]
Hello!
Ubuntu 22.04.4 LTS , AMD® Ryzen 5 5625u

64,65 snap version Can't start caprine via snap. 
Previous 2.59.< 63 is's working fine.

$ snap list caprine  --all
Name     Version  Rev  Tracking       Publisher     Notes
caprine  2.59.2   64   latest/stable  sindresorhus  disabled
caprine  2.59.3   65   latest/stable  sindresorhus  -
-------------------------------------------------------------
$ caprine --verbose

Verbose log:
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/snap/caprine/65/resources/app.asar/node_modules/conf/dist/source/index.js:67:43)
    at get store [as store] (/snap/caprine/65/resources/app.asar/node_modules/conf/dist/source/index.js:278:43)
    at new Conf (/snap/caprine/65/resources/app.asar/node_modules/conf/dist/source/index.js:131:32)
    at new ElectronStore (/snap/caprine/65/resources/app.asar/node_modules/electron-store/index.js:69:3)
    at Object.<anonymous> (/snap/caprine/65/resources/app.asar/dist-js/config.js:231:15)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)

(caprine:16264): Gtk-WARNING **: 11:46:08.930: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(caprine:16264): Gtk-WARNING **: 11:46:08.933: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(caprine:16264): Gtk-WARNING **: 11:46:08.933: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
**/usr/share/libdrm/amdgpu.ids: No such file or directory**
-----------------------------------------------------------------------------
$ snap info caprine
Caprine info:
snap info caprine
name:      caprine
summary:   Caprine
publisher: Sindre Sorhus (sindresorhus)
store-url: https://snapcraft.io/caprine
license:   unset
description: |
  Caprine is an unofficial and privacy-focused Facebook Messenger app with many useful features.
commands:
  - caprine
snap-id:      UluDLd64Rry6IYTesGapYwu8sfuZmwbu
tracking:     latest/stable
refresh-date: today at 07:57 CET
channels:
  latest/stable:    2.59.3 2024-02-20 (65) 89MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      ↑                           
installed:          2.59.3            (65) 89MB -

snap connections caprine
Interface                 Plug                     Slot                             Notes
audio-playback            caprine:audio-playback   :audio-playback                  -
browser-support           caprine:browser-support  :browser-support                 -
camera                    caprine:camera           -                                -
content[gnome-3-28-1804]  caprine:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     caprine:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      caprine:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     caprine:sound-themes     gtk-common-themes:sound-themes   -
desktop                   caprine:desktop          :desktop                         -
desktop-legacy            caprine:desktop-legacy   :desktop-legacy                  -
gsettings                 caprine:gsettings        :gsettings                       -
home                      caprine:home             :home                            -
network                   caprine:network          :network                         -
opengl                    caprine:opengl           :opengl                          -
pulseaudio                caprine:pulseaudio       :pulseaudio                      -
removable-media           caprine:removable-media  -                                -
unity7                    caprine:unity7           :unity7                          -
wayland                   caprine:wayland          :wayland                         -
x11                       caprine:x11              :x11                             -

**Comment by dusansimic** [comment]
Thanks for reporting the issue! This seems to be a fairly common thing https://github.com/canonical/steam-snap/pull/321 https://github.com/snapcrafters/scummvm/issues/31 [snapcraft forum](https://forum.snapcraft.io/t/apps-from-snap-cannot-access-usr-share-libdrm-amdgpu-ids/31672/9).

I've used the solution from the steam-snap repo and build a new snap package. Could you try it out and see if the issue is fixed?

https://send.vis.ee/download/c80e86ad6651406a/#7_boiqeR7HCHQsjT2V9ZHA
