### ISSUE TITLE
App fails to open

### ISSUE THREAD

**Issue by hawkins** [sindresorhus/caprine#283]
> Hey, love the app, have been using it for a couple months now, so I just wanted to say great work as always. This is the first issue I've ever had with the app  🙌 

---

Running on MacOS 10.12.6

---

Recently the app began failing to open for me. No error message or anything, but it just doesn't open. I've tried updating to the latest version via downloading from GitHub releases, but the issue persists.

Not sure if this is related or caused by the unusual starting method, but I tried running the app from the terminal as such:

```
$ cd /Applications/Caprine.app/Contents/MacOS
$ ./Caprine
Wait for app ready
/Applications/Caprine.app/Contents/Resources/electron.asar/common/reset-search-paths.js:0



Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Caprine.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/Applications/Caprine.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/Applications/Caprine.app/Contents/Resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process.emit (/Applications/Caprine.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:431:21)
    at process._fatalException (bootstrap_node.js:300:26)
```

... and again, it failed to open.

Any idea what's up, or how I could further debug this?

**Comment by sindresorhus** [comment]
Does it work when launched normally?

**Comment by hawkins** [comment]
No, it fails silently in that case as well

**Comment by hawkins** [comment]
Have tried reinstalling and using older versions as well, but all seem to have the same result of silent failure.

**Comment by zipy124** [comment]
I'm also having this issue, Fedora 29 the app just doesn't open at all

**Comment by chrishiste** [comment]
Same problem for me since 2 days, the app is stuck on a white screen. I tried updating manually as well but no difference.

**Comment by hawkins** [comment]
That actually seems a different problem from mine - the app opens then immediately closes.

**Comment by chrishiste** [comment]
In the meantime you can do like me and use Goofy instead. But I prefer Caprine so if I figure out a fix, I will share it here.

**Comment by macrophone** [comment]
Same problem for me now. 
I'm using Caprine on Debian 10 installed via snap packages.
Running latest/stable:   2.44.0 2020-02-05
Doesn't start for several weeks, maybe since update but unsure.
