### ISSUE TITLE
Crashes on startup on Linux

### ISSUE THREAD

**Issue by rwhogg** [sindresorhus/caprine#37]
As of version 0.5.0, Caprine crashes on Linux after starting up. It looks like the issue is related to the new tray icon.

When you start up, it displays a pop-up window displaying the following message:
Uncaught Exception:
TypeError: Error processing argument -1.
    at TypeError (native)
    at module.exports.win (/home/bob/software/caprine/resources/app/tray.js:11:15)
    at EventEmitter.<anonymous> (/home/bob/software/caprine/resources/app/index.js:76:2)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

As I was writing this issue, I discovered the solution. Will post a patch in a few minutes.

**Comment by sindresorhus** [comment]
Ugh, the only time I don't test on Linux, because my Ubuntu VM is borked, this happens. Thanks for reporting :)
