### ISSUE TITLE
TypeError: Invalid Version: undefined

### ISSUE THREAD

**Issue by ivanovsaleksejs** [sindresorhus/caprine#569]
Time after time an alert box appears with this error:

```
TypeError: Invalid Version: undefined
    at new SemVer (/nix/store/2yf14svjj8110419maka7cjs034r2yb5-messenger-for-desktop-2.0.6/libexec/resources/app.asar/node_modules/semver/semver.js:279:11)
    at compare (/nix/store/2yf14svjj8110419maka7cjs034r2yb5-messenger-for-desktop-2.0.6/libexec/resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/nix/store/2yf14svjj8110419maka7cjs034r2yb5-messenger-for-desktop-2.0.6/libexec/resources/app.asar/node_modules/semver/semver.js:595:10)
    at /nix/store/2yf14svjj8110419maka7cjs034r2yb5-messenger-for-desktop-2.0.6/libexec/resources/app.asar/scripts/browser/components/auto-updater/base.js:79:49
    at done (/nix/store/2yf14svjj8110419maka7cjs034r2yb5-messenger-for-desktop-2.0.6/libexec/resources/app.asar/node_modules/needle/lib/needle.js:429:14)
    at PassThrough.<anonymous> (/nix/store/2yf14svjj8110419maka7cjs034r2yb5-messenger-for-desktop-2.0.6/libexec/resources/app.asar/node_modules/needle/lib/needle.js:668:11)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
### System info

 - OS: NixOS 18.03.132821.56fad146a12 (Impala) x86_64
 - Host: 80VG Lenovo YOGA 910-13IKB Glass
 - Kernel: 4.14.53
 - Uptime: 20 days, 6 hours, 10 mins
 - Packages: 6797
 - Shell: bash 4.4.12
 - Resolution: 1920x1080
 - WM: i3
 - Theme: Breeze-Dark [GTK2/3]
 - Icons: Adwaita [GTK2/3]
 - Terminal: ..terminator-wr
 - CPU: Intel i7-7500U (4) @ 3.500GHz
 - Memory: 5534MiB / 7726MiB

### nix-info

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.53, NixOS, 18.03.132821.56fad146a12 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(root): `"nixos-18.03.132821.56fad146a12"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs

**Comment by sindresorhus** [comment]
Can you make sure you're using the latest Caprine version?
