### ISSUE TITLE
Caprine doesn't start

### ISSUE THREAD

**Issue by SoptikHa2** [sindresorhus/caprine#647]
Today, I launched caprine and it didn't work - there was just white screen after startup. Starting with terminal found the issue:

```
$ caprine 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
[17:34:17.722] [info] Checking for update
[17:34:17.967] [error] Error: Error: ENOENT: no such file or directory, open '/snap/caprine/6/resources/app-update.yml'
    at /snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:427:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:423:33)
    at Lazy.AppUpdater.configOnDisk (/snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:138:43)
    at Lazy.get value [as value] (/snap/caprine/6/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:339:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at AppImageUpdater.checkForUpdates (/snap/caprine/6/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at Object.<anonymous> (/snap/caprine/6/resources/app.asar/index.js:37:14)
    at Object.<anonymous> (/snap/caprine/6/resources/app.asar/index.js:393:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Object.<anonymous> (/snap/caprine/6/resources/electron.asar/browser/init.js:189:8)
    at Object.<anonymous> (/snap/caprine/6/resources/electron.asar/browser/init.js:191:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
^C
```

I believe new version was uploaded recently?

Reinstalling the snap didn't work, I cannot write to the folder since it is marked as read-only filesystem and I don't know how should the file look like.

If someone can tell me how should the file look I should be able [to do it](https://askubuntu.com/a/1036611) (not tested).

---

Caprine 2.21.0
Electron 3.0.6
linux x64 4.15.0-38-generic

**Comment by SoptikHa2** [comment]
Suddenly fixed itself.

**Comment by regineblanco** [comment]
Have the same prob. Deleted and downloaded yet it still just shows a blank screen

**Comment by SoptikHa2** [comment]
I'm afraid I cannot help you. It fixed itself for me. There is still no `app-update.yml` anywhere, but it works for me. If it doesn't fix itself in a day or two, maybe consider adding here some debug info, and in that case I'll reopen the issue.
