### ISSUE TITLE
Error changing to dark mode

### ISSUE THREAD

**Issue by rafakwolf** [sindresorhus/caprine#730]
Changing to dark mode:
```
Uncaught Exception:
Error: EACCES: permission denied, open '/home/rafael/snap/caprine/14/.config/Caprine/config.json.428594929'
    at Object.openSync (fs.js:436:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:160:31)
    at Function.writeFileSync [as sync] (/snap/caprine/14/resources/app.asar/node_modules/write-file-atomic/index.js:180:17)
    at ElectronStore.set store [as store] (/snap/caprine/14/resources/app.asar/node_modules/conf/index.js:167:19)
    at ElectronStore.set (/snap/caprine/14/resources/app.asar/node_modules/conf/index.js:81:14)
    at click (/snap/caprine/14/resources/app.asar/menu.js:251:11)
    at MenuItem.click (/snap/caprine/14/resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/snap/caprine/14/resources/electron.asar/browser/api/menu.js:31:13)
```

---

Caprine 2.26.0
Electron 4.0.1
linux 4.15.0-43-generic
Locale: pt-BR

**Comment by rafakwolf** [comment]
updating to 2.27 the issue is gone
