### ISSUE TITLE
Icons not included into build

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/caprine#754]
Since the codebase update to TypeScript, theres been an error when running Caprine (`npm start`). The icons from `static` folder are not included into the build for some reason. The process starts but Caprine window doesn't open.

Here's the log.

```
(node:2974) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 0, conversion failure from /home/dusan/dev/caprine/dist-js/static/IconTray.png
    at Object.create (/home/dusan/dev/caprine/dist-js/tray.js:42:16)
    at /home/dusan/dev/caprine/dist-js/index.js:231:20
(node:2974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've tested this just on Linux (Ubuntu 18.10 with Gnome 3.30.1).

**Comment by CvX** [comment]
Good catch, thanks for the report! 🙂  I've pushed the fix in #755.
