### ISSUE TITLE
Caprine Deb Package Crashes on Linux

### ISSUE THREAD

**Issue by tgm-git** [sindresorhus/caprine#913]
OS: Debian 10 buster
Kernel: x86_64 Linux 4.199.0-5-amd64

When I installed the caprine deb package I get the same error as in  [another issue](https://github.com/sindresorhus/caprine/issues/887), however, since the chrome-sand box isn't a temporary file I can change ownership and permissions.

This fixed the first problem.

Once I ran it afterwards I got the following error:

```
[error] Error: Error: ENOENT: no such file or directory, open '/opt/Caprine/resources/app-update.yml'
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
    at Lazy.<anonymous> (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
    at Lazy.get value [as value] (/opt/Caprine/resources/app.asar/node_modules/lazy-val/src/main.ts:18:25)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at Object.<anonymous> (/opt/Caprine/resources/app.asar/source/index.ts:67:14)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Object.<anonymous> (/opt/Caprine/resources/electron.asar/browser/init.js:197:8)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:873:10)
    at internal/main/run_main_module.js:21:11
Unhandled rejection Error: ENOENT: no such file or directory, open '/opt/Caprine/resources/app-update.yml'
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
    at Lazy.<anonymous> (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
    at Lazy.get value [as value] (/opt/Caprine/resources/app.asar/node_modules/lazy-val/src/main.ts:18:25)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at Object.<anonymous> (/opt/Caprine/resources/app.asar/source/index.ts:67:14)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Object.<anonymous> (/opt/Caprine/resources/electron.asar/browser/init.js:197:8)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:873:10)
    at internal/main/run_main_module.js:21:11
```

**Comment by tripkin** [comment]
I can confirm. Just had the same happen to me... Changed the chrome-sanbox to mode 4755, and then in a terminal also got the message about the missing 'app-update.yml'. There were also two lines above the posted error message that are missing and my be relevant:
`[00:10:28.985] [info] Checking for update
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[error] Error: Error: ENOENT: no such file or directory, open '/opt/Caprine/resources/app-update.yml'
...
`

**Comment by tgm-git** [comment]
This issue seams to be caused by this [issue](https://github.com/electron/electron/issues/17972) in electron.
