### ISSUE TITLE
2.33.0 - Multiple startup errors - font warning, TypeError: Cannot read property 'provider' of undefined, Unhandled promise rejection

### ISSUE THREAD

**Issue by dotpointer** [sindresorhus/caprine#966]
Debian MATE 9.9.
Caprine current version 2.33.0, previous version 2.27.

If I run `caprine` as a regular user from a terminal I get this output:

```
16:59:27.406 › Checking for update
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
16:59:27.873 › Error: TypeError: Cannot read property 'provider' of undefined
    at createClient (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/providerFactory.ts:19:25)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:63
From previous event:
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:52
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at /opt/Caprine/resources/app.asar/source/index.ts:64:21
    at Object.<anonymous> (/opt/Caprine/resources/app.asar/source/index.ts:65:4)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Object.<anonymous> (/opt/Caprine/resources/electron.asar/browser/init.js:197:8)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:873:10)
    at internal/main/run_main_module.js:21:11
(node:25204) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'provider' of undefined
    at createClient (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/providerFactory.ts:19:25)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:63
From previous event:
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:52
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at /opt/Caprine/resources/app.asar/source/index.ts:64:21
    at Object.<anonymous> (/opt/Caprine/resources/app.asar/source/index.ts:65:4)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Object.<anonymous> (/opt/Caprine/resources/electron.asar/browser/init.js:197:8)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:873:10)
    at internal/main/run_main_module.js:21:11
(node:25204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`/etc/fonts/fonts.conf` has not changed since 2018-07 and the lines around 100 looks like this:
```
<config>
<!--
These are the default Unicode chars that are expected to be blank
in fonts.  All other blank chars are assumed to be broken and
won't appear in the resulting charsets
-->
<blank>
<int>0x0020</int>       <!-- SPACE -->
<int>0x00A0</int>       <!-- NO-BREAK SPACE -->
```
The application loads as it should anyway.

**Comment by alekksander** [comment]
quite similar here:

23:47:16.537 › Checking for update
23:47:17.057 › Error: Error: ENOENT: no such file or directory, open '/opt/Caprine/resources/app-update.yml'
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
    at Lazy.<anonymous> (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
    at Lazy.get value [as value] (/opt/Caprine/resources/app.asar/node_modules/lazy-val/src/main.ts:18:25)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at /opt/Caprine/resources/app.asar/source/index.ts:64:21
    at Object.<anonymous> (/opt/Caprine/resources/app.asar/source/index.ts:65:4)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Object.<anonymous> (/opt/Caprine/resources/electron.asar/browser/init.js:197:8)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:873:10)
    at internal/main/run_main_module.js:21:11
(node:2187) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/opt/Caprine/resources/app-update.yml'
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
    at Lazy.<anonymous> (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
    at Lazy.get value [as value] (/opt/Caprine/resources/app.asar/node_modules/lazy-val/src/main.ts:18:25)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/opt/Caprine/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at /opt/Caprine/resources/app.asar/source/index.ts:64:21
    at Object.<anonymous> (/opt/Caprine/resources/app.asar/source/index.ts:65:4)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Object.<anonymous> (/opt/Caprine/resources/electron.asar/browser/init.js:197:8)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:873:10)
    at internal/main/run_main_module.js:21:11
(node:2187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2187) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by CvX** [comment]
Alright, there are exactly two things here:

**1. `Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"`**

That’s a Chromium warning. You can read more about it here: https://unix.stackexchange.com/questions/504335/fontconfig-warning-etc-fonts-fonts-conf-line-100-unknown-element-blank (_TLDR: nothing to worry about_)

**2. `Error: TypeError: Cannot read property 'provider' of undefined` and `Error: Error: ENOENT: no such file or directory, open '/opt/Caprine/resources/app-update.yml'`**

These both relate to a missing app update config. There seems to be a bug in (or misconfiguration of) electron-builder. The `app-update.yml` is correctly generated for Mac build, but apparently is missing in AppImage build, and also in Snap and/or Deb.

I found those potential solutions/workarounds: https://github.com/electron-userland/electron-builder/issues/2736#issuecomment-456380922 (adding placeholders `publish` values to build target configurations) and https://github.com/electron-userland/electron-builder/issues/2667#issuecomment-371107620 (similarly, adding a `publish` property to `win` section).

Paging @sindresorhus! 😉
